// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDem_G5tfhqAV1Jsmmkgo9HLI9Aqs4cPV4',
    appId: '1:189770472674:web:c177b8b417f2c758a452bb',
    messagingSenderId: '189770472674',
    projectId: 'indore-vypaar-ai',
    authDomain: 'indore-vypaar-ai.firebaseapp.com',
    storageBucket: 'indore-vypaar-ai.firebasestorage.app',
    measurementId: 'G-TE4JZDCD8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDLOIUi_4zbhIYqghQudhWEVA8SRKcGx0',
    appId: '1:189770472674:android:3fa09065e5b2d0a9a452bb',
    messagingSenderId: '189770472674',
    projectId: 'indore-vypaar-ai',
    storageBucket: 'indore-vypaar-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVU9q-vBwDW0imuXy00vvKyPKzDqvjFhg',
    appId: '1:189770472674:ios:62fb69d98b740a33a452bb',
    messagingSenderId: '189770472674',
    projectId: 'indore-vypaar-ai',
    storageBucket: 'indore-vypaar-ai.firebasestorage.app',
    iosBundleId: 'com.example.indoreVypaarAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVU9q-vBwDW0imuXy00vvKyPKzDqvjFhg',
    appId: '1:189770472674:ios:62fb69d98b740a33a452bb',
    messagingSenderId: '189770472674',
    projectId: 'indore-vypaar-ai',
    storageBucket: 'indore-vypaar-ai.firebasestorage.app',
    iosBundleId: 'com.example.indoreVypaarAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDem_G5tfhqAV1Jsmmkgo9HLI9Aqs4cPV4',
    appId: '1:189770472674:web:6ab1ef1a0df00956a452bb',
    messagingSenderId: '189770472674',
    projectId: 'indore-vypaar-ai',
    authDomain: 'indore-vypaar-ai.firebaseapp.com',
    storageBucket: 'indore-vypaar-ai.firebasestorage.app',
    measurementId: 'G-CVT5SJNS0D',
  );

}